export const ANALYSIS_PROFILES = [
  {
    name: 'quick',
    label: 'Quick Scan',
    description: 'Fast & cheap. Good for checking if a game loads.',
    model: 'claude-sonnet-4-5-20250929',
    synthesisModel: 'gemini-3-flash-preview',
    maxTokens: 8192,
    agentSteps: 15,
    temperature: 0.2,
    adaptive: false,
    maxTotalSteps: 0,
    adaptiveTimeout: false,
    maxTotalTimeout: 0,
    cost: 'low',
    time: '3–8 min',
  },
  {
    name: 'balanced',
    label: 'Balanced',
    description: 'Default. Good balance of speed, cost, and quality.',
    model: 'claude-sonnet-4-5-20250929',
    synthesisModel: 'gemini-3-flash-preview',
    maxTokens: 8192,
    agentSteps: 40,
    temperature: 0.3,
    adaptive: true,
    maxTotalSteps: 60,
    adaptiveTimeout: true,
    maxTotalTimeout: 25,
    cost: 'medium',
    time: '10–20 min',
  },
  {
    name: 'thorough',
    label: 'Thorough',
    description: 'Adaptive exploration with dynamic step and timeout extension for complex games.',
    model: 'claude-sonnet-4-5-20250929',
    synthesisModel: 'gemini-3-flash-preview',
    maxTokens: 16384,
    agentSteps: 50,
    temperature: 0.3,
    adaptive: true,
    maxTotalSteps: 100,
    adaptiveTimeout: true,
    maxTotalTimeout: 45,
    cost: 'high',
    time: '15–35 min',
  },
  {
    name: 'maximum',
    label: 'Maximum',
    description: 'Best quality. Maximum adaptive exploration for complex games.',
    model: 'claude-sonnet-4-5-20250929',
    synthesisModel: 'gemini-3-flash-preview',
    maxTokens: 16384,
    agentSteps: 60,
    temperature: 0.2,
    adaptive: true,
    maxTotalSteps: 150,
    adaptiveTimeout: true,
    maxTotalTimeout: 60,
    cost: 'very high',
    time: '20–50 min',
  },
  {
    name: 'debug',
    label: 'Debug',
    description: 'Minimal. For debugging the pipeline quickly.',
    model: 'claude-sonnet-4-5-20250929',
    synthesisModel: 'gemini-3-flash-preview',
    maxTokens: 4096,
    agentSteps: 3,
    temperature: 0.1,
    adaptive: false,
    maxTotalSteps: 0,
    adaptiveTimeout: false,
    maxTotalTimeout: 0,
    cost: 'minimal',
    time: '1–3 min',
  },
]

export function getProfileByName(name) {
  return ANALYSIS_PROFILES.find((p) => p.name === name) || null
}
